### ISSUE TITLE
Request for changes

### ISSUE THREAD

**Issue by gergelytraveltime** [Mindzks/igeoliseFirstTask#1]
Could you please apply some changes in this repo?

1. `private List<Double> coordinates;` - you should use a proper Coordinate class
2. getters and setters - objects should be immutable
3. `private List<List<List<Double>>> coordinates;` - instead of nested lists, please use proper classes for each data type (e.g. MultiPolygon)
4. `private List<String> matched_locations;`, `public void setMatched_locations` - please follow proper naming conventions (camelCase)
5. `double x1 = polyPoint1.get(0);` - please add polygon and coordinate validation
6. Please add error handling
7. `addMatcehdLocation` please spellcheck your code
8. Add unit tests
9. Please clean up packages:  some files are in org/example. The rest was left in the root.
10. Please add .gitignore; e.g. target should be in gitignore and should not be committed

**Comment by Mindzks** [comment]
Ajusted code according to your feedback.
